apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: postgres-credentials
  namespace: vote  # Must match your app namespace
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "dev/vote/postgres"  # Your secret name in AWS Secrets Manager
        objectType: "secretsmanager"
        jmesPath:
          - path: "POSTGRES_USER"  # exact key defined in secret Manager
          - objectAlias: "db_user"  # clean name instead of encoded aws name 
          - path: "POSTGRES_PASSWORD" 
          - objectAlias: "db_passwd"
    
  secretObjects:
    - secretName: vote-postgres-secrets
      type: Opaque
      data:
        - objectName: db_user     # object alias defined  above 
          key: POSTGRES_USER     # env var that we want in pods 
        - objectName: db_passwd
          key: POSTGRES_PASSWORD
        






