---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: vote
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: voting-ebs-sc
  resources:
    requests:
      storage: 1Gi