apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        resources:
          limits:
            cpu: "1000m"    # 1 CPU core
            memory: "512Mi"  # 512 Megabytes
          requests:
            cpu: "500m"     # 0.5 CPU cores
            memory: "256Mi"  # 256 Megabytes
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-secret
              key: POSTGRES_PASSWORD
        - name: PGDATA
          value: /var/lib/postgresql/storage/pgdata         
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: vote-cm
              key: POSTGRES_USER
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: vote-cm
              key: POSTGRES_DATABASE
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/storage
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc



---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: vote
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432